### ISSUE TITLE
Add Thousand separator inside CastVistor NUMBER/INTEGER -> STRING

### ISSUE THREAD

**Issue by laurentC35** [InseeFr/Trevas-JS#115]
To make a large number displayed to the user more readable when using a VTL formula mixing text and number.

__*Actual behavior*__:
_input_ : `"You've just won " || cast(1000000, string) || " euros !" `
_output_ : `You've just won 1000000 euros !`

__*Expected behavior*__:
_input_ : `"You've just won " || cast(1000000, string) || " euros !" `
_output_ : `You've just won 1,000,000 euros !` / `You've just won 1 000 000 euros !` (Fr thousand separator)

An easy way to do this would be to use the JS function [`toLocalString()`](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Number/toLocaleString) in the [CastVisitor](https://github.com/InseeFr/Trevas-JS/blob/master/packages/trevas/src/visitors/functions/Cast.js#L41).

```js
[VtlParser.INTEGER, VtlParser.STRING, (op) => op?.toLocalString() || `${op}`],
...,
[VtlParser.NUMBER, VtlParser.STRING, (op) => op?.toLocalString() || `${op}`],
```

**Comment by NicoLaval** [comment]
Indeed it's not complicated but it is a grammar issue.
Please, reference your issue in the https://github.com/VTL-Community/VTL-Community repository to have a larger discussion.
