### ISSUE TITLE
`instr` function may not work as expected

### ISSUE THREAD

**Issue by romaintailhurat** [InseeFr/Trevas-JS#124]
If we are to believe [the VTL spec](https://sdmx.org/wp-content/uploads/VTL-2.0-Reference-Manual-20180712-final.pdf), the `instr` function should return:

```
instr("124", "3") → 0
instr("124", "1") → 1
```

but instead it actually returns:

```
instr("124", "3") → 0
instr("124", "1") → 0
```

so we are not able to distinguish  between string patterns that are not here and string patterns starting at the 1st position (`1` in VTL, not `0`). 🥴 

It's probably just a +1 problem with JS indexes.

**Comment by NicoLaval** [comment]
Fix 33416b6c6e35ff4192495ddda06b99a1a0a3b043
