### ISSUE TITLE
DATE_FORMAT support

### ISSUE THREAD

**Issue by NicoLaval** [InseeFr/Trevas-JS#30]
1998-07-12 is recognized as a DATE_FORMAT and ctx.getText() returns the date as well.

When I try with 1998-11-12, the context just give 1998-11.

VtlTokens.g4 contains DATE_FORMAT with MONTH and DAY types (not the same syntax, sometimes parenthesis, sometimes not), I try to play with and building tools, without success.

**Comment by hadrienk** [comment]
This might linked to the unary/numerical constant issue #33 (-12 recognized as negative integer).

**Comment by hadrienk** [comment]
Both the `DATE_FORMAT` and `TIME_FORMAT` tokens are not used. This result in Lexer errors: `cast(1998-07-12, string, "YYYY-DD-MM")` results in unrecognized token `DATE_TOKEN` (this is not reported by the [lexer](https://stackoverflow.com/questions/18491563/accumulating-lexer-errors-in-antlr-4))

**Comment by vignola** [comment]
Hi Hadrienk,
could you please clarify better the issue?
Thanks

**Comment by hadrienk** [comment]
The aforementioned tokens are only defined, never used by the grammar. This results in unexpected tokens I'm the example

**Comment by vignola** [comment]
I am sorry Hadrienk, I wanted to comment for clarification, the issue "The stringOperators rule is ambiguous" #41, no this one.
Sorry for the mistake

**Comment by FranckCo** [comment]
Moved to https://github.com/VTL-Community/VTL-Community/issues/11.
