### ISSUE TITLE
Number / Float clarifications

### ISSUE THREAD

**Issue by hadrienk** [InseeFr/Trevas-JS#36]
The Spec document calls float types "number", no mentions of float in the document.

However, the user manual defines - from a syntax perspective - numbers as fixed point numbers (???) if they are **not** represented with mantissa: 123.456 but as floating point if defined with mantissa (scientific notation): 12345.6E2. 

Similarly, integers (without decimal then) are defined as either floating point integer (not sure what this is) or fixed point integer. 

This is rather odd and should be fixed.

**Comment by FranckCo** [comment]
Moved to https://github.com/VTL-Community/VTL-Community/issues/14.
