### ISSUE TITLE
The stringOperators rule is ambiguous

### ISSUE THREAD

**Issue by hadrienk** [InseeFr/Trevas-JS#41]
The alternative `instrAtom` in the rule `stringOperators` is ambiguous. Optional parameters need to be imbricated.

Example of ambiguous expression: `instr("Hello world world", "world", 11)`

https://github.com/InseeFr/VTL-Tools/blob/e45f3761f838e73978d914ab9cface4d0a80cfc4/vtl-sources/Vtl-3.0-Istat/Vtl.g4#L173

```
INSTR LPAREN expr COMMA param=expr ( COMMA optionalExpr (COMMA optionalExpr)?)?  RPAREN	# instrAtom
```

**Comment by FranckCo** [comment]
Moved to https://github.com/VTL-Community/VTL-Community/issues/13.
