### ISSUE TITLE
For June 2021: Age calculation: converting a date (especially the current date) into a string

### ISSUE THREAD

**Issue by FabiennePG** [InseeFr/Trevas-JS#71]
To calculate the age of a respondent, we would need to be able to convert a date, and in particular the current date, into a string in order to be able to extract the corresponding year, month and day via the substr() function.
In principle, we aim to use the syntax cast(current_date(), string) in VTL to convert for example the current date into a string.
We aim to use the syntax cast(date,number) also to compare 2 dates together or the operators < <= > >= to compare 2 dates together.

**Comment by FranckCo** [comment]
Casting between dates and strings (in both directions) is now implemented. The issue boils down to implementing comparisons between dates.

**Comment by NicoLaval** [comment]
Fixed e756434bbd38cee8b32c8dcd316706d4617a6d96
