### ISSUE TITLE
Management of regular expressions (match_character)

### ISSUE THREAD

**Issue by FabiennePG** [InseeFr/Trevas-JS#73]
Some controls on the questionnaires require checking that certain non-empty answers are assimilable to a number (telephone number, siren, siret) in particular.To do this, the match_character function could be appropriate to check that a given textual variable verifies a certain regular expression (in this case that it only contains numbers).

**Comment by FranckCo** [comment]
VTL defines a match_characters operator (line 4096 of the RM), so this is to implement in Trevas_JS.

**Comment by NicoLaval** [comment]
Fixed e16b778ae2e4a4ec7651f55e75e51fc1a7f91763
